# ==============================================================================
# docker-compose.base.yml - Base Infrastructure Services
# ==============================================================================
# Purpose: Database, cache, and core infrastructure for cluster
# Composition: PostgreSQL, MariaDB, Memcached, Redis
# Network: mcp-cluster (shared with all other services)
# Testing: docker-compose -f docker-compose.base.yml up
# ==============================================================================

# Include database service configurations from their respective directories
include:
  - path: ../databases/postgres/docker-compose.postgres.yml
  - path: ../databases/mariadb/docker-compose.mariadb.yml

# Volumes are defined in main docker-compose.yml to avoid conflicts

services:

  # ==== TIER 4: Cache Layer ====

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    hostname: memcached
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.60
    ports:
      - "11211:11211"
    command: memcached -m 256 -p 11211
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.61
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - react_scuba_redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.62
    ports:
      - "5540:5540"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5540/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
