# ==============================================================================
# PostgreSQL Service Configuration
# ==============================================================================
# Purpose: PostgreSQL 16 database service
# Location: .devcontainer/infrastructure/databases/postgres/
# Usage: Referenced by main compose files
# ==============================================================================

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    hostname: postgres-db
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD:-password}
      - POSTGRES_INITDB_ARGS=-c max_connections=200
    volumes:
      - react_scuba_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
