# ==============================================================================
# Sealed Secret for Grafana Admin Credentials
# ==============================================================================
# Generate using: kubectl create secret generic grafana-credentials \
#   --from-literal=admin-user=admin \
#   --from-literal=admin-password=<strong-password> \
#   --dry-run=client -o yaml | kubeseal -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: CHANGE_ME_BEFORE_SEALING
