version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - db
      - node
      - python
    networks:
      - basic-stack-network

  node:
    image: node:20-alpine
    volumes:
      - ../..:/app:cached
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - basic-stack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  python:
    image: python:3.14-slim
    volumes:
      - ../..:/app:cached
    working_dir: /app
    command: sh -c "pip install -r python_utils/requirements.txt && python -m python_utils.doc_utils"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - basic-stack-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - basic-stack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  basic-stack-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
