# ==============================================================================
# docker-compose.yml - React Scuba Full Stack Orchestration
# ==============================================================================
#
# Single command deployment: docker compose up
# Includes core service tiers via modular compose fragments
# MCP services managed separately in docker-compose.mcp-persistent.yml
#
# USAGE:
#   docker compose up              # Start core stack (base + app + infra + gpu)
#   docker compose up --build     # Start with build
#   docker compose --profile no-gpu up  # Start without GPU services
#
# MCP SERVICES (separate):
#   docker compose -f docker-compose.mcp-persistent.yml up -d --profile mcp
#

include:
  - .devcontainer/infrastructure/compose/base.yml
  - .devcontainer/infrastructure/compose/app.yml
  - .devcontainer/infrastructure/compose/infra.yml
  - .devcontainer/infrastructure/compose/gpu.yml

# Named volumes for persistence (shared across all fragments)
volumes:
  # ==== Database Volumes ====
  react_scuba_postgres-data:
    name: react_scuba_postgres-data
  react_scuba_postgres-node-cache:
    name: react_scuba_postgres-node-cache
  react_scuba_postgres-cache:
    name: react_scuba_postgres-cache
  react_scuba_mariadb-data:
    name: react_scuba_mariadb-data
  react_scuba_mariadb-node-cache:
    name: react_scuba_mariadb-node-cache
  react_scuba_mariadb-cache:
    name: react_scuba_mariadb-cache

  # ==== Cache Volumes ====
  react_scuba_redis-data:
    name: react_scuba_redis-data
  react_scuba_redisinsight-data:
    name: react_scuba_redisinsight-data
  react_scuba_minio-data:
    name: react_scuba_minio-data

  # ==== Build & Development Volumes ====
  react_scuba_buildkit-cache:
    name: react_scuba_buildkit-cache
  react_scuba_buildkit-tmp:
    name: react_scuba_buildkit-tmp
  react_scuba_node-builder-node-modules:
    name: react_scuba_node-builder-node-modules
  react_scuba_node-builder-npm:
    name: react_scuba_node-builder-npm
  react_scuba_node-builder-git-hooks:
    name: react_scuba_node-builder-git-hooks
  react_scuba_node-builder-husky:
    name: react_scuba_node-builder-husky
  react_scuba_node-bootstrap-cache:
    name: react_scuba_node-bootstrap-cache

  # ==== CI/CD Volumes ====
  react_scuba_runner-work:
    name: react_scuba_runner-work
  react_scuba_runner-cache:
    name: react_scuba_runner-cache

  # ==== Infrastructure Volumes ====
  react_scuba_prometheus-data:
    name: react_scuba_prometheus-data
  react_scuba_grafana-data:
    name: react_scuba_grafana-data
  react_scuba_nginx-logs:
    name: react_scuba_nginx-logs
  react_scuba_nginx-slave1-logs:
    name: react_scuba_nginx-slave1-logs
  react_scuba_nginx-slave2-logs:
    name: react_scuba_nginx-slave2-logs

  # ==== API & Application Volumes ====
  react_scuba_api-logs:
    name: react_scuba_api-logs
  react_scuba_api-data:
    name: react_scuba_api-data

  # ==== GPU & AI Volumes ====
  # Ollama models stored in C:/shared_memory/ollama-cache (centralized host cache)

  # ==== MCP Volumes ====
  react_scuba_mcp-discovery-cache:
    name: react_scuba_mcp-discovery-cache
  react_scuba_markitdown-cache:
    name: react_scuba_markitdown-cache
  react_scuba_mcp-memory-cache:
    name: react_scuba_mcp-memory-cache

  # ==== Workspace Node Modules ====
  react_scuba_root_node_modules:
    name: react_scuba_root_node_modules
  react_scuba_web_node_modules:
    name: react_scuba_web_node_modules
  react_scuba_api_node_modules:
    name: react_scuba_api_node_modules
  react_scuba_content_node_modules:
    name: react_scuba_content_node_modules
  react_scuba_docs_node_modules:
    name: react_scuba_docs_node_modules
  react_scuba_config_node_modules:
    name: react_scuba_config_node_modules
  react_scuba_types_node_modules:
    name: react_scuba_types_node_modules
  react_scuba_ui_node_modules:
    name: react_scuba_ui_node_modules
  react_scuba_utils_node_modules:
    name: react_scuba_utils_node_modules
  react_scuba_react-vite-cache:
    name: react_scuba_react-vite-cache
  react_scuba_react-npm-cache:
    name: react_scuba_react-npm-cache

  # ==== Development Volumes ====
  react_scuba_devcontainer-cache:
    name: react_scuba_devcontainer-cache
  react_scuba_python-exp-cache:
    name: react_scuba_python-exp-cache
  react_scuba_k8s-config:
    name: react_scuba_k8s-config
  react_scuba_k8s-cache:
    name: react_scuba_k8s-cache

# Network configuration (shared by all included services)
networks:
  mcp-cluster:
    name: mcp-cluster
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
