# ==============================================================================
# Namespace-scoped Roles for Tenant Isolation
# ==============================================================================
# Per-tenant Roles for resource access within namespace only

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-app-role
  namespace: apps
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get"]
    resourceNames:
      - db-credentials
      - github-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
  namespace: databases
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
    verbs: ["get", "create"]

  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs: ["get", "list"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "create"]
