# ==============================================================================
# Node.js Web Dev Server Configuration
# ==============================================================================
# Purpose: Vite development server with HMR for React frontend
# Location: .devcontainer/infrastructure/services/web/
# Usage: docker compose -f docker-compose.web.yml up
# Ports: 3001 (app), 5173 (Vite HMR), 5174 (Vite secondary)
# ==============================================================================

services:
  node-web:
    build:
      context: ../../../../..
      dockerfile: .devcontainer/infrastructure/services/web/dockerfile
    image: react-scuba-web:latest
    pull_policy: build
    container_name: node-web
    hostname: node-web
    profiles:
      - full
      - app
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.65
    ports:
      - "3001:3001"
      - "5173:5173"
      - "5174:5174"
    env_file:
      - ../../../../../devcontainer.env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
    volumes:
      - ../../../../../server/apps/web/src:/app/server/apps/web/src
      - ../../../../../server/packages:/app/server/packages
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
        reservations:
          cpus: "1.0"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.react-scuba.service=node-web"