# yaml-language-server: disable=true
# ==============================================================================
# Production API Patches
# ==============================================================================
# Full HA with higher resource limits

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: apps
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-api-hpa
  namespace: apps
spec:
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
