# ==============================================================================
# Production Environment Overlay
# ==============================================================================
# Full HA configuration with production TLS

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

bases:
  - ../../base/apps
  - ../../base/databases
  - ../../base/cache
  - ../../base/monitoring
  - ../../base/networking

patchesStrategicMerge:
  - api-patches.yaml
  - web-patches.yaml
  - ingress-patches.yaml

commonLabels:
  environment: production

# Images use semantic versioning for production
images:
  - name: localhost:5001/react-scuba-api
    newTag: v1.0.0
  - name: localhost:5001/react-scuba-web
    newTag: v1.0.0
