version: "3.8"

services:
  node:
    build:
      context: ../..
      dockerfile: docker-compose-examples/swarm-stack/dockerfiles/node.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npx vite preview --port 3000 --host 0.0.0.0
    depends_on:
      - db
    networks:
      - swarm-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://127.0.0.1:3000/ || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s

  python:
    build:
      context: ../..
      dockerfile: docker-compose-examples/swarm-stack/dockerfiles/python.Dockerfile
    volumes:
      - ../..:/app:cached
      - python_venv:/app/.venv
      - python_cache:/root/.cache/pip
    working_dir: /app
    command: sh -c "pip install -r python_utils/requirements.txt && python -m python_utils.doc_utils inventory"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - swarm-network
    healthcheck:
      test:
        ["CMD", "python", "-c", "import sys; print('Python OK'); sys.exit(0)"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres.Dockerfile
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - swarm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
    driver: local
  db_logs:
    driver: local
  node_modules:
    driver: local
  python_venv:
    driver: local
  python_cache:
    driver: local

networks:
  swarm-network:
    driver: bridge
