version: "3.8"

services:
  loadbalancer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8080:80"
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx:alpine
    volumes:
      - ./web-content:/usr/share/nginx/html
    command: nginx -g 'daemon off;'

  web2:
    image: nginx:alpine
    volumes:
      - ./web-content:/usr/share/nginx/html
    command: nginx -g 'daemon off;'

  web3:
    image: nginx:alpine
    volumes:
      - ./web-content:/usr/share/nginx/html
    command: nginx -g 'daemon off;'

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
