apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-ingress.yaml
  - 01-cert-manager-letsencrypt-staging.yaml
  - 02-cert-manager-letsencrypt-prod.yaml

commonLabels:
  managed-by: kustomize
  component: networking
