# ==============================================================================
# Nginx Ingress Controller Installation
# ==============================================================================
# Helm-based installation via kustomization

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
data:
  # Performance tuning
  worker-processes: "auto"
  max-worker-connections: "65536"

  # Security headers
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"

  # Rate limiting
  limit-req-status-code: "429"

  # Logging
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id $tenant_id'
---
# Installation via Helm (apply after kind cluster setup)
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install ingress-nginx ingress-nginx/ingress-nginx \
#   --namespace ingress-nginx \
#   --create-namespace \
#   --set controller.service.type=NodePort \
#   --set controller.service.nodePorts.http=30080 \
#   --set controller.service.nodePorts.https=30443 \
#   --set controller.metrics.enabled=true \
#   --set controller.podLabels.tenant=shared
