service:
  name: fetch-mcp
  type: mcp-server

network:
  ip: 172.20.0.35

resources:
  cpu: 1
  memory: 1g

volumes:
  - fetch-cache:/cache/fetch
  - fetch-pip-cache:/cache/pip
  - fetch-python-cache:/cache/python
  - fetch-http-cache:/cache/http

optimization:
  http2: true
  network: 1gb-tuned
