# ==============================================================================
# Jaeger Distributed Tracing
# ==============================================================================
# All-in-one deployment for distributed tracing across services

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001

      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.51
          ports:
            - containerPort: 5775
              protocol: UDP
              name: zipkin-compact
            - containerPort: 6831
              protocol: UDP
              name: jaeger-compact
            - containerPort: 6832
              protocol: UDP
              name: jaeger-binary
            - containerPort: 5778
              name: configs
            - containerPort: 16686
              name: query
            - containerPort: 14268
              name: collector
            - containerPort: 14269
              name: admin
            - containerPort: 9411
              name: zipkin

          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: PROMETHEUS_SERVER_URL
              value: http://prometheus.monitoring.svc.cluster.local:9090
            - name: SPAN_STORAGE_TYPE
              value: memory

          livenessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - port: 14268
      targetPort: 14268
      name: collector
    - port: 9411
      targetPort: 9411
      name: zipkin

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - port: 16686
      targetPort: 16686
      name: query

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
spec:
  selector:
    app: jaeger
  ports:
    - port: 5775
      protocol: UDP
      targetPort: 5775
      name: zipkin-compact
    - port: 6831
      protocol: UDP
      targetPort: 6831
      name: jaeger-compact
    - port: 6832
      protocol: UDP
      targetPort: 6832
      name: jaeger-binary
    - port: 5778
      targetPort: 5778
      name: configs
