# Grafana Datasource Provisioning Configuration
# Format: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
# This file configures Prometheus as the default datasource for Grafana

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy  
    url: http://prometheus:9090
    isDefault: true
    editable: false