service:
  name: mariadb-mcp
  type: mcp-server

network:
  ip: 172.20.0.32

resources:
  cpu: 1
  memory: 2g
  max_size: 500m

volumes:
  - mariadb-node-cache:/cache/node
  - mariadb-cache:/cache/mariadb

dependencies:
  - mariadb
