services:
  app:
    build: .
    volumes:
      - ../..:/workspaces:cached
      - react-scuba-node_modules:/workspaces/${localWorkspaceFolderBasename}/node_modules
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  react-scuba-node_modules:
  db_data:
