# ==============================================================================
# Python MCP Server Configuration
# ==============================================================================
# Purpose: Python MCP sidecar service with persistent state
# Location: .devcontainer/infrastructure/mcp-servers/python/
# Usage: docker compose -f docker-compose.python-mcp.yml up
# Testing: curl http://localhost:9099/health
# ==============================================================================

services:
  python-mcp-sidecar:
    build:
      context: ../../../../../docker-compose-examples/mcp/python_utils
      dockerfile: ../../../.devcontainer/infrastructure/mcp-servers/python/dockerfile
      args:
        PYTHON_VERSION: "3.14t"
        UV_VERSION: "latest"
    image: python-mcp-sidecar:latest
    container_name: python-mcp-sidecar
    hostname: python-mcp-sidecar
    profiles:
      - full
      - minimal
      - mcp
    networks:
      mcp-cluster:
        ipv4_address: 172.29.0.99
    ports:
      - "9099"
    env_file:
      - ../../../../../devcontainer.env
    environment:
      - ENABLE_MCP=${ENABLE_MCP:-false}
      - MCP_HTTP_PORT=9099
      - MCP_PROTOCOL_VERSION=1.0.0
      - PYTHONUNBUFFERED=1
      - UV_SYSTEM_PYTHON=1
      - PYTHON_GIL_MODE=1
    volumes:
      - ../../../../../docker-compose-examples/mcp/python_utils:/app:ro
      - python_mcp_packages:/usr/local/lib/python3.14/site-packages
      - python_mcp_state:/data
      - python_mcp_cache:/cache/python
      - python_mcp_uv_cache:/cache/uv
    working_dir: /app
    command: ["python", "-m", "utils.mcp_server"]
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "python", "-m", "utils.health", "--protocol-validation", "--endpoint", "http://localhost:9099/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "com.react-scuba.service=python-mcp"