# Prometheus Configuration for MCP Cluster Monitoring
# Reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 10s
  scrape_timeout: 8s
  evaluation_interval: 10s
  external_labels:
    cluster: "mcp-cluster"
    environment: "development"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"
          tier: "monitoring"

  # cAdvisor - Container metrics (detailed)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: "cadvisor"
          tier: "monitoring"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "container_(cpu|memory|network|fs).*"
        action: keep

  # Node Exporter - Host system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "node-exporter"
          tier: "monitoring"

  # PostgreSQL Exporter
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgresql"
          tier: "database"

  # MySQL/MariaDB Exporter
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
        labels:
          service: "mariadb"
          tier: "database"

  # MCP Cluster Services
  - job_name: "docker-containers"
    static_configs:
      - targets:
          - "postgres-db:5432"
          - "mariadb:3306"
          - "postgres-mcp:3000"
          - "mariadb-mcp:3000"
          - "k8s-plugin:8080"
          - "buildkit:1234"
          - "devcontainer:8080"
        labels:
          cluster: "mcp"
          tier: "application"

  # Nginx monitoring
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
        labels:
          service: "nginx"
          tier: "gateway"

  # Grafana self-monitoring
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          service: "grafana"
          tier: "monitoring"
