apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

resources:
  - postgres-cluster.yaml
  - mariadb-galera.yaml
  - backup-jobs.yaml

commonLabels:
  tier: database
  managed-by: kustomize
