# ==============================================================================
# Ollama LLM Inference Server Configuration
# ==============================================================================
# Purpose: Local LLM inference with GPU acceleration
# Location: .devcontainer/infrastructure/services/ollama/
# Usage: docker compose -f docker-compose.ollama.yml up
# Requirements: NVIDIA GPU with 6GB+ VRAM
# Ports: 11435 (API), 9401 (metrics)
# Models: smollm2:latest, codegeex4:9b-all-q3_K_M, mistral:latest
# ==============================================================================

services:
  ollama-llm:
    build:
      context: .
      dockerfile: dockerfile
    image: ollama-llm:latest
    pull_policy: build
    container_name: ollama-llm
    hostname: ollama-llm
    profiles:
      - full
      - gpu
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.59
    ports:
      - "11435:11434"
      - "9401:9401"
    env_file:
      - ../../../../../devcontainer.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.react-scuba.service=ollama-llm"