service:
  name: memory-mcp
  type: mcp-server

network:
  ip: 172.20.0.33

resources:
  cpu: 1
  memory: 4g

volumes:
  - memory-data:/memory
  - memory-node-cache:/cache/node
  - memory-cache:/cache/memory

optimization:
  nvme: true
