service:
  name: git-mcp
  type: mcp-server

network:
  ip: 172.20.0.34

resources:
  cpu: 1
  memory: 1g

volumes:
  - git-cache:/cache/git
  - git-pip-cache:/cache/pip
  - git-python-cache:/cache/python

features:
  - git-lfs
  - libgit2
