# ==============================================================================
# Nginx Master Reverse Proxy Configuration
# ==============================================================================
# Purpose: Primary reverse proxy and load balancer
# Location: .devcontainer/infrastructure/networking/nginx/
# Usage: docker compose -f docker-compose.nginx.yml up
# Ports: HTTP:8080, HTTPS:8443, Health:8088
# ==============================================================================

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    image: nginx-proxy:latest
    pull_policy: build
    container_name: nginx
    hostname: nginx
    profiles:
      - full
      - loadbalancing
    networks:
      mcp-cluster:
        ipv4_address: 172.28.0.73
    ports:
      - "8443:443"
      - "8080:80"
      - "8088:8080"
    volumes:
      - nginx-logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    labels:
      - "com.react-scuba.service=nginx"

volumes:
  nginx-logs:
    name: nginx-logs
