# ==============================================================================
# Development Web Patches
# ==============================================================================
# Reduced resources for dev

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
  namespace: apps
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
