service:
  name: k8s-plugin
  type: tools

network:
  ip: 172.20.0.50

tools:
  - kubectl: v1.31.2
  - helm: v3.16.2
  - kompose: v1.34.0
  - k9s: v0.32.5

volumes:
  - k8s-config:/root/.kube
  - k8s-cache:/cache/k8s
  - /var/run/docker.sock:/var/run/docker.sock
