global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'docker-containers'
    static_configs:
      - targets: 
        - 'postgres-db:5432'
        - 'mariadb:3306'
        - 'postgres-mcp:3000'
        - 'mariadb-mcp:3000'
        - 'k8s-plugin:8080'
        - 'buildkit:1234'
        - 'devcontainer:8080'
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']