apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

# Base resources to inherit from
bases:
  - ../../base/apps
  - ../../base/configmaps

# Tenant-specific resources
resources:
  - configmap-api.yaml
  - configmap-web.yaml
  - ingress.yaml

# Apply tenant labels to all resources
commonLabels:
  tenant: "${TENANT_ID}"
  managed-by: argocd

# Patch base deployments with tenant configuration
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: node-api
      namespace: apps
    spec:
      template:
        metadata:
          labels:
            tenant: "${TENANT_ID}"
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: node-web
      namespace: apps
    spec:
      template:
        metadata:
          labels:
            tenant: "${TENANT_ID}"

# Image overrides (optional - use specific versions per tenant)
# images:
#   - name: localhost:5001/react-scuba-api
#     newTag: "${TENANT_ID}-v1.0.0"
#   - name: localhost:5001/react-scuba-web
#     newTag: "${TENANT_ID}-v1.0.0"
